### ISSUE TITLE
[Feature Request] Support 1.20.2

### ISSUE THREAD

**Issue by Potothingi** [jpenilla/AnnouncerPlus#182]
**Is your feature request related to a problem? Please describe.**
```
[18:29:29 INFO]: [AnnouncerPlus] Enabling AnnouncerPlus v1.3.5
[18:29:30 ERROR]: Error occurred while enabling AnnouncerPlus v1.3.5 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at xyz.jpenilla.announcerplus.AnnouncerPlus.initToastTask(AnnouncerPlus.kt:115) ~[AnnouncerPlus-1.3.5.jar:?]
        at xyz.jpenilla.announcerplus.AnnouncerPlus.enable(AnnouncerPlus.kt:88) ~[AnnouncerPlus-1.3.5.jar:?]
        at xyz.jpenilla.announcerplus.lib.xyz.jpenilla.pluginbase.legacy.PluginBase.onEnable(PluginBase.java:49) ~[AnnouncerPlus-1.3.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-201]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-201]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-201]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-201]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-201]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-201]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-201]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-201]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-201]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Cannot find Advancement$Builder#build
        at xyz.jpenilla.announcerplus.task.ToastTask.<clinit>(ToastTask.kt:174) ~[AnnouncerPlus-1.3.5.jar:?]
        ... 15 more
[18:29:30 INFO]: [AnnouncerPlus] Disabling AnnouncerPlus v1.3.5
```

**Describe the solution you'd like**
1.20.2 Support update

**Describe alternatives you've considered**
1.20.2 Support update

**Comment by jpenilla** [comment]
The [latest dev build](https://jenkins.jpenilla.xyz/job/AnnouncerPlus/lastSuccessfulBuild/) will load on 1.20.2, but without toast support for now
