### ISSUE TITLE
[Bug Report] /ap sendtoast fails with error

### ISSUE THREAD

**Issue by tmfksoft** [jpenilla/AnnouncerPlus#219]
**Describe the bug**
When running the /ap sendtoast command nothing happens and the following trace shows:

```
[12:35:36 INFO]: MajesticFudgie issued server command: /announcer sendtoast MajesticFudgie netherite_helmet goal "Header here" "Body Here"
[12:35:36 WARN]: [AnnouncerPlus] Plugin AnnouncerPlus v1.3.7 generated an exception while executing task 155
java.lang.IncompatibleClassChangeError: Found interface com.mojang.serialization.DataResult, but class was expected
        at AnnouncerPlus-1.3.7.jar/xyz.jpenilla.announcerplus.task.ToastTask.buildAdvancement(ToastTask.kt:131) ~[AnnouncerPlus-1.3.7.jar:?]
        at AnnouncerPlus-1.3.7.jar/xyz.jpenilla.announcerplus.task.ToastTask.displayToasts(ToastTask.kt:93) ~[AnnouncerPlus-1.3.7.jar:?]
        at AnnouncerPlus-1.3.7.jar/xyz.jpenilla.announcerplus.task.ToastTask.poll(ToastTask.kt:72) ~[AnnouncerPlus-1.3.7.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.6.jar:1.20.6-82-0ad09de]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.6.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

**To Reproduce**
1. Run /ap sendtoast command
2. Nothing happens in game, stack trace in console

**Expected behavior**
Toast displays

**Screenshots**
N/A

**Server Software and Version:**
 - Vendor: Paper
 - Minecraft Version: 1.20.6
 - Output of /version command: This server is running Paper version 1.20.6-82-master@0ad09de (2024-05-18T20:25:01Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
 - Plugin Version: 1.3.7 (Latest GH Version/Release)

**Additional context**

**Comment by jpenilla** [comment]
1.20.6 is not yet supported in the release version
