### ISSUE TITLE
[Bug Report] Toast feature does not work

### ISSUE THREAD

**Issue by SentorCraft** [jpenilla/AnnouncerPlus#241]
**Describe the bug**
[15:55:24 ERROR]: [AnnouncerPlus] Exception executing task
java.lang.NoSuchMethodException: net.minecraft.server.dedicated.DedicatedServer.registryAccess()
        at java.lang.Class.getMethod(Class.java:2395) ~[?:?]
        at xyz.jpenilla.announcerplus.task.ToastTask$DFU.registryOps_delegate$lambda$0(ToastTask.kt:163) ~[AnnouncerPlus-1.4.0 (1).jar:?]
        at xyz.jpenilla.announcerplus.lib.kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[AnnouncerPlus-1.4.0 (1).jar:?]
        at xyz.jpenilla.announcerplus.task.ToastTask$DFU.getRegistryOps(ToastTask.kt:161) ~[AnnouncerPlus-1.4.0 (1).jar:?]
        at xyz.jpenilla.announcerplus.task.ToastTask$DFU.registryOps(ToastTask.kt:171) ~[AnnouncerPlus-1.4.0 (1).jar:?]
        at xyz.jpenilla.announcerplus.task.ToastTask.buildAdvancement(ToastTask.kt:131) ~[AnnouncerPlus-1.4.0 (1).jar:?]
        at xyz.jpenilla.announcerplus.task.ToastTask.displayToasts(ToastTask.kt:94) ~[AnnouncerPlus-1.4.0 (1).jar:?]
        at xyz.jpenilla.announcerplus.task.ToastTask.poll(ToastTask.kt:73) ~[AnnouncerPlus-1.4.0 (1).jar:?]
        at xyz.jpenilla.announcerplus.util.ExtensionsKt.wrapRunnable$lambda$4(extensions.kt:123) ~[AnnouncerPlus-1.4.0 (1).jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**To Reproduce**
1. Use any command that produces toast announcements (sendtoast / broadcasttoast)
**Expected behavior**
Toast announcements should work.

**Screenshots**

**Server Software and Version:**
 - Vendor: Purpur
 - Minecraft Version: 1.20.4
 - Output of /version command: Current: git-Purpur-2176 (MC: 1.20.4)** You are running the latest version

**Additional context**

**Comment by jpenilla** [comment]
use the dev builds or update paper
